name: hello-world-2nd
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:

    
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed



      - name: my-step-2nd time
        run: |
          python start.py
          echo "Hello World!"
          echo "I am from HK"
